/**
 * Built-in prompt banks for the art games. Everything here should be drawable
 * in under two minutes by someone with no artistic talent whatsoever.
 */

/** Default word pool for Guess the Word and Swap Artist prompts. */
export const DEFAULT_WORDS: readonly string[] = [
  // animals
  'cat', 'dog', 'elephant', 'giraffe', 'penguin', 'octopus', 'butterfly', 'snail',
  'shark', 'whale', 'crab', 'jellyfish', 'owl', 'bat', 'spider', 'snake',
  'turtle', 'frog', 'bee', 'ladybug', 'flamingo', 'hedgehog', 'kangaroo', 'panda',
  'monkey', 'lion', 'tiger', 'zebra', 'horse', 'sheep', 'pig', 'chicken',
  'duck', 'fish', 'dinosaur', 'dragon', 'unicorn', 'mermaid',
  // food & drink
  'pizza', 'hamburger', 'hot dog', 'taco', 'sushi', 'spaghetti', 'pancake', 'waffle',
  'ice cream', 'cupcake', 'donut', 'cookie', 'birthday cake', 'popcorn', 'pretzel',
  'apple', 'banana', 'watermelon', 'pineapple', 'strawberry', 'grapes', 'carrot',
  'broccoli', 'mushroom', 'cheese', 'egg', 'bacon', 'sandwich', 'burrito',
  'coffee', 'milkshake', 'lemonade', 'teapot',
  // objects
  'umbrella', 'backpack', 'glasses', 'crown', 'ladder', 'anchor', 'balloon', 'candle',
  'clock', 'compass', 'dice', 'envelope', 'feather', 'flashlight', 'hammer', 'key',
  'kite', 'lightbulb', 'magnet', 'microphone', 'mirror', 'paperclip', 'pillow',
  'scissors', 'stapler', 'suitcase', 'telescope', 'toothbrush', 'trophy', 'wallet',
  'wheelbarrow', 'zipper', 'book', 'camera', 'guitar', 'piano', 'drum', 'violin',
  'trumpet', 'skateboard', 'bicycle', 'roller skates', 'sled', 'tent', 'campfire',
  'fishing rod', 'binoculars', 'treasure chest', 'robot', 'rocket', 'satellite',
  'traffic light', 'mailbox', 'fire hydrant', 'street lamp', 'park bench', 'fountain',
  // places & nature
  'beach', 'island', 'volcano', 'mountain', 'waterfall', 'desert', 'iceberg', 'cave',
  'castle', 'lighthouse', 'windmill', 'barn', 'bridge', 'skyscraper', 'igloo',
  'pyramid', 'ferris wheel', 'roller coaster', 'playground', 'garden', 'forest',
  'rainbow', 'tornado', 'lightning', 'snowman', 'sandcastle', 'sun', 'moon', 'star',
  'planet', 'comet', 'cloud', 'tree', 'cactus', 'flower', 'sunflower', 'mushroom house',
  // people & fantasy
  'pirate', 'ninja', 'wizard', 'witch', 'knight', 'astronaut', 'cowboy', 'clown',
  'chef', 'firefighter', 'detective', 'ghost', 'vampire', 'zombie', 'alien',
  'superhero', 'ballerina', 'juggler', 'king', 'queen', 'baby', 'scarecrow', 'angel',
  // vehicles
  'car', 'bus', 'train', 'airplane', 'helicopter', 'sailboat', 'submarine',
  'hot air balloon', 'tractor', 'ambulance', 'fire truck', 'police car', 'motorcycle',
  'canoe', 'spaceship', 'pirate ship', 'ufo',
  // actions & concepts
  'sleeping', 'dancing', 'singing', 'swimming', 'fishing', 'camping', 'surfing',
  'skiing', 'juggling', 'sneezing', 'yawning', 'karate', 'yoga', 'high five',
  'hide and seek', 'tug of war', 'selfie', 'dream', 'love', 'luck', 'time travel',
  'gravity', 'echo', 'shadow', 'winter', 'summer', 'birthday', 'wedding', 'parade',
];

/**
 * Imposter prompt pairs: close enough that the imposter's drawing blends in,
 * different enough that sharp eyes can catch it.
 */
export const IMPOSTER_PAIRS: readonly (readonly [string, string])[] = [
  ['hairbrush', 'toothbrush'],
  ['cat', 'fox'],
  ['apple', 'tomato'],
  ['shark', 'dolphin'],
  ['violin', 'guitar'],
  ['moon', 'sun'],
  ['pizza', 'pie'],
  ['snowman', 'scarecrow'],
  ['bee', 'wasp'],
  ['duck', 'goose'],
  ['coffee cup', 'teacup'],
  ['castle', 'sandcastle'],
  ['helicopter', 'airplane'],
  ['pancake', 'waffle'],
  ['spider', 'crab'],
  ['wizard', 'witch'],
  ['lighthouse', 'rocket'],
  ['donut', 'bagel'],
  ['penguin', 'owl'],
  ['ladder', 'stairs'],
  ['rain', 'snow'],
  ['lion', 'tiger'],
  ['cupcake', 'muffin'],
  ['ghost', 'snowman'],
  ['turtle', 'snail'],
  ['bicycle', 'motorcycle'],
  ['fork', 'trident'],
  ['balloon', 'bubble'],
  ['mouse', 'hamster'],
  ['river', 'road'],
  ['glasses', 'binoculars'],
  ['crown', 'tiara'],
  ['sock', 'glove'],
  ['candle', 'torch'],
  ['whale', 'submarine'],
  ['tent', 'pyramid'],
  ['butterfly', 'moth'],
  ['squirrel', 'chipmunk'],
  ['hot dog', 'burrito'],
  ['drum', 'barrel'],
  ['zebra', 'horse'],
  ['tornado', 'ice cream cone'],
  ['knight', 'astronaut'],
  ['envelope', 'flag'],
  ['pirate', 'ninja'],
  ['carrot', 'pencil'],
  ['igloo', 'turtle shell'],
  ['clock', 'compass'],
  ['broom', 'mop'],
  ['cloud', 'sheep'],
  ['key', 'wrench'],
  ['strawberry', 'raspberry'],
  ['volcano', 'mountain'],
  ['angel', 'fairy'],
  ['train', 'caterpillar'],
  ['mermaid', 'fish'],
  ['campfire', 'birthday cake'],
  ['skateboard', 'surfboard'],
  ['robot', 'knight'],
  ['kite', 'paper airplane'],
];
