/**
 * Hand-authored bank of 5×5 mini crosswords. The GRID is the source of
 * truth: every across and down reading was verified to be a real, common
 * English word before its clue was written, and intersections are
 * consistent by construction. Clue numbers follow standard crossword
 * numbering, which the engine re-derives from the grid shape — the
 * engine.test.ts bank validation asserts the numbers here match 1:1.
 *
 * Three shapes are used (all runs are 3–5 letters; no 2-letter words):
 *   staircase-left   ##··· / #···· / ····· / ····# / ···##
 *   staircase-right  ···## / ····# / ····· / #···· / ##···
 *   corner-cut       #···· / ····· / ····· / ····· / ····#
 */

export interface CrosswordClue {
  num: number;
  clue: string;
}

export interface CrosswordPuzzle {
  /** 5 strings of 5 chars: '#' = black square, 'A'–'Z' = solution letter. */
  grid: string[];
  cluesAcross: CrosswordClue[];
  cluesDown: CrosswordClue[];
}

export const PUZZLES: CrosswordPuzzle[] = [
  {
    // FUR / VERY / RANGE / ONCE / BEE — FENCE / URGE / RYE / VANE / ROB
    grid: ['##FUR', '#VERY', 'RANGE', 'ONCE#', 'BEE##'],
    cluesAcross: [
      { num: 1, clue: 'Coat on a cat' },
      { num: 4, clue: 'Extremely' },
      { num: 5, clue: 'Kitchen stove, or a cowboy’s home' },
      { num: 6, clue: 'A single time' },
      { num: 7, clue: 'Spelling contest' },
    ],
    cluesDown: [
      { num: 1, clue: 'Backyard boundary' },
      { num: 2, clue: 'Strong impulse' },
      { num: 3, clue: 'Deli bread choice' },
      { num: 4, clue: 'Weather pointer on a barn roof' },
      { num: 5, clue: 'Hold up, as a bank' },
    ],
  },
  {
    // PUT / RIPE / SALON / IRON / PET — PILOT / UPON / TEN / RARE / SIP
    grid: ['##PUT', '#RIPE', 'SALON', 'IRON#', 'PET##'],
    cluesAcross: [
      { num: 1, clue: 'Set down' },
      { num: 4, clue: 'Ready to eat, as a banana' },
      { num: 5, clue: 'Where to get a haircut' },
      { num: 6, clue: 'Wrinkle remover' },
      { num: 7, clue: 'Dog or cat, often' },
    ],
    cluesDown: [
      { num: 1, clue: 'Cockpit occupant' },
      { num: 2, clue: 'Once ___ a time' },
      { num: 3, clue: 'Perfect gymnastics score' },
      { num: 4, clue: 'Barely cooked, as a steak' },
      { num: 5, clue: 'Tiny taste of tea' },
    ],
  },
  {
    // RAY / RATE / PIVOT / ITEM / TEN — RAVEN / ATOM / YET / RITE / PIT
    grid: ['##RAY', '#RATE', 'PIVOT', 'ITEM#', 'TEN##'],
    cluesAcross: [
      { num: 1, clue: 'Beam of sunshine' },
      { num: 4, clue: 'Stars-out-of-five score' },
      { num: 5, clue: 'Basketball footwork, or a startup’s change of plan' },
      { num: 6, clue: 'To-do list entry' },
      { num: 7, clue: 'Number of bowling pins' },
    ],
    cluesDown: [
      { num: 1, clue: 'Poe’s “Nevermore” bird' },
      { num: 2, clue: 'Smallest bit of an element' },
      { num: 3, clue: 'So far' },
      { num: 4, clue: '___ of passage' },
      { num: 5, clue: 'Peach’s center' },
    ],
  },
  {
    // SEE / SWAY / THESE / ROPE / YET — SWEPT / EASE / EYE / SHOE / TRY
    grid: ['##SEE', '#SWAY', 'THESE', 'ROPE#', 'YET##'],
    cluesAcross: [
      { num: 1, clue: 'Perceive with the eyes' },
      { num: 4, clue: 'Move like palms in the wind' },
      { num: 5, clue: 'Not those, but ___' },
      { num: 6, clue: 'Tug-of-war need' },
      { num: 7, clue: 'Up to now' },
    ],
    cluesDown: [
      { num: 1, clue: 'Used a broom' },
      { num: 2, clue: 'Do it “with ___” and it looks effortless' },
      { num: 3, clue: 'A needle has one' },
      { num: 4, clue: 'Sneaker or loafer' },
      { num: 5, clue: 'Give it a shot' },
    ],
  },
  {
    // COD / CUBE / ARROW / COVE / EWE — CURVE / OBOE / DEW / CROW / ACE
    grid: ['##COD', '#CUBE', 'ARROW', 'COVE#', 'EWE##'],
    cluesAcross: [
      { num: 1, clue: 'Fish in fish and chips' },
      { num: 4, clue: 'Ice shape' },
      { num: 5, clue: 'Archer’s projectile' },
      { num: 6, clue: 'Sheltered bay' },
      { num: 7, clue: 'Female sheep' },
    ],
    cluesDown: [
      { num: 1, clue: 'Bend in the road' },
      { num: 2, clue: 'Reed instrument that tunes the orchestra' },
      { num: 3, clue: 'Morning droplets on grass' },
      { num: 4, clue: 'Bird that caws' },
      { num: 5, clue: 'Unbeatable tennis serve' },
    ],
  },
  {
    // HUG / NONE / PERIL / REST / ODE — HORSE / UNIT / GEL / NEED / PRO
    grid: ['##HUG', '#NONE', 'PERIL', 'REST#', 'ODE##'],
    cluesAcross: [
      { num: 1, clue: 'Warm embrace' },
      { num: 4, clue: 'Zilch' },
      { num: 5, clue: 'Grave danger' },
      { num: 6, clue: 'Take a breather' },
      { num: 7, clue: 'Poem of praise' },
    ],
    cluesDown: [
      { num: 1, clue: 'Trojan ___' },
      { num: 2, clue: 'Apartment, in real-estate listings' },
      { num: 3, clue: 'Hair goop' },
      { num: 4, clue: 'Require' },
      { num: 5, clue: 'Expert, informally' },
    ],
  },
  {
    // JAW / EXAM / TIGER / SOME / NOD — JET / AXIS / WAGON / MEMO / RED
    grid: ['JAW##', 'EXAM#', 'TIGER', '#SOME', '##NOD'],
    cluesAcross: [
      { num: 1, clue: 'It drops when you’re amazed' },
      { num: 4, clue: 'Final at the end of a semester' },
      { num: 6, clue: 'Striped big cat' },
      { num: 8, clue: 'A few' },
      { num: 9, clue: 'Silent yes' },
    ],
    cluesDown: [
      { num: 1, clue: 'Very fast plane' },
      { num: 2, clue: 'X or Y line on a graph' },
      { num: 3, clue: 'Little red pull-along' },
      { num: 5, clue: 'Office note' },
      { num: 7, clue: 'Stoplight color' },
    ],
  },
  {
    // NET / AXIS / PIANO / TRAP / APT — NAP / EXIT / TIARA / SNAP / OPT
    grid: ['NET##', 'AXIS#', 'PIANO', '#TRAP', '##APT'],
    cluesAcross: [
      { num: 1, clue: 'Tennis court divider' },
      { num: 4, clue: 'Earth spins on one' },
      { num: 6, clue: '88-key instrument' },
      { num: 8, clue: 'Mouse catcher' },
      { num: 9, clue: 'Fitting' },
    ],
    cluesDown: [
      { num: 1, clue: 'Afternoon snooze' },
      { num: 2, clue: 'Way out' },
      { num: 3, clue: 'Pageant crown' },
      { num: 5, clue: 'Finger click, or an easy task' },
      { num: 7, clue: 'Choose (to)' },
    ],
  },
  {
    // FIR / ATOM / REBEL / MINE / NUT — FAR / ITEM / ROBIN / MENU / LET
    grid: ['FIR##', 'ATOM#', 'REBEL', '#MINE', '##NUT'],
    cluesAcross: [
      { num: 1, clue: 'Christmas tree, often' },
      { num: 4, clue: 'Tiny building block of matter' },
      { num: 6, clue: 'Rule breaker' },
      { num: 8, clue: '“That one’s not yours, it’s ___!”' },
      { num: 9, clue: 'Cashew or almond' },
    ],
    cluesDown: [
      { num: 1, clue: 'A long way off' },
      { num: 2, clue: 'Shopping-list entry' },
      { num: 3, clue: 'Red-breasted herald of spring' },
      { num: 5, clue: 'Restaurant offering' },
      { num: 7, clue: 'Allow' },
    ],
  },
  {
    // COD / OMIT / BEGAN / NICE / TOW — COB / OMEN / DIGIT / TACO / NEW
    grid: ['COD##', 'OMIT#', 'BEGAN', '#NICE', '##TOW'],
    cluesAcross: [
      { num: 1, clue: 'Cape ___, Massachusetts' },
      { num: 4, clue: 'Leave out' },
      { num: 6, clue: 'Got started' },
      { num: 8, clue: 'Pleasant' },
      { num: 9, clue: 'Haul, as a broken-down car' },
    ],
    cluesDown: [
      { num: 1, clue: 'Corn holder' },
      { num: 2, clue: 'Sign of things to come' },
      { num: 3, clue: 'Finger, toe, or numeral' },
      { num: 5, clue: 'Folded Mexican fare' },
      { num: 7, clue: 'Fresh off the shelf' },
    ],
  },
  {
    // ZAP / ICON / PILOT / DATA / RED — ZIP / ACID / POLAR / NOTE / TAD
    grid: ['ZAP##', 'ICON#', 'PILOT', '#DATA', '##RED'],
    cluesAcross: [
      { num: 1, clue: 'Microwave, informally' },
      { num: 4, clue: 'Desktop clickable' },
      { num: 6, clue: 'TV show’s first episode' },
      { num: 8, clue: 'Spreadsheet fodder' },
      { num: 9, clue: 'Rose’s color, often' },
    ],
    cluesDown: [
      { num: 1, clue: 'Zero, in slang' },
      { num: 2, clue: 'Lemon juice, chemically' },
      { num: 3, clue: '___ bear' },
      { num: 5, clue: 'Post-it message' },
      { num: 7, clue: 'Wee bit' },
    ],
  },
  {
    // SEE / PALM / ARBOR / LOVE / WED — SPA / EARL / ELBOW / MOVE / RED
    grid: ['SEE##', 'PALM#', 'ARBOR', '#LOVE', '##WED'],
    cluesAcross: [
      { num: 1, clue: '“___ you later!”' },
      { num: 4, clue: 'Beach tree, or part of a hand' },
      { num: 6, clue: 'Ann ___, Michigan' },
      { num: 8, clue: 'Zero, in tennis' },
      { num: 9, clue: 'Tie the knot' },
    ],
    cluesDown: [
      { num: 1, clue: 'Massage venue' },
      { num: 2, clue: '___ Grey tea' },
      { num: 3, clue: 'Funny bone’s joint' },
      { num: 5, clue: 'Chess turn' },
      { num: 7, clue: 'Fire-engine color' },
    ],
  },
  {
    // PAST / SINCE / WAGON / INEPT / MOLE — PIANO / ANGEL / SCOPE / TENT / SWIM
    grid: ['#PAST', 'SINCE', 'WAGON', 'INEPT', 'MOLE#'],
    cluesAcross: [
      { num: 1, clue: 'History, collectively' },
      { num: 5, clue: 'From then until now' },
      { num: 6, clue: 'Covered ___ (pioneer’s ride)' },
      { num: 7, clue: 'Hopelessly clumsy' },
      { num: 8, clue: 'Backyard burrower' },
    ],
    cluesDown: [
      { num: 1, clue: 'Grand instrument' },
      { num: 2, clue: 'Halo wearer' },
      { num: 3, clue: 'Rifle attachment, or a project’s extent' },
      { num: 4, clue: 'Camper’s shelter' },
      { num: 5, clue: 'Do laps in a pool' },
    ],
  },
  {
    // MEET / HELLO / UDDER / NIECE / TART — MEDIA / ELDER / ELECT / TORE / HUNT
    grid: ['#MEET', 'HELLO', 'UDDER', 'NIECE', 'TART#'],
    cluesAcross: [
      { num: 1, clue: 'Track-and-field event' },
      { num: 5, clue: 'Adele hit, or a greeting' },
      { num: 6, clue: 'Milk source on a cow' },
      { num: 7, clue: 'Sibling’s daughter' },
      { num: 8, clue: 'Sharp-tasting, like some apples' },
    ],
    cluesDown: [
      { num: 1, clue: 'The press, collectively' },
      { num: 2, clue: 'Senior member' },
      { num: 3, clue: 'Choose by ballot' },
      { num: 4, clue: 'Ripped' },
      { num: 5, clue: 'Search (for)' },
    ],
  },
  {
    // SOAP / WHALE / EASEL / SKIRT / TEST — SHAKE / OASIS / ALERT / PELT / WEST
    grid: ['#SOAP', 'WHALE', 'EASEL', 'SKIRT', 'TEST#'],
    cluesAcross: [
      { num: 1, clue: 'Suds maker' },
      { num: 5, clue: 'Largest animal on Earth (blue one)' },
      { num: 6, clue: 'Painter’s stand' },
      { num: 7, clue: 'Garment, or to dodge (an issue)' },
      { num: 8, clue: 'Pop quiz, e.g.' },
    ],
    cluesDown: [
      { num: 1, clue: 'Milkshake, minus the milk?' },
      { num: 2, clue: 'Desert watering hole' },
      { num: 3, clue: 'Phone buzz, e.g.' },
      { num: 4, clue: 'Animal hide' },
      { num: 5, clue: 'Sunset direction' },
    ],
  },
  {
    // STIR / SHONE / TAKEN / ALERT / BENT — SHALE / TOKEN / INERT / RENT / STAB
    grid: ['#STIR', 'SHONE', 'TAKEN', 'ALERT', 'BENT#'],
    cluesAcross: [
      { num: 1, clue: 'Mix with a spoon' },
      { num: 5, clue: 'Gleamed' },
      { num: 6, clue: 'Spoken for' },
      { num: 7, clue: 'Wide-awake' },
      { num: 8, clue: 'Not straight' },
    ],
    cluesDown: [
      { num: 1, clue: 'Layered sedimentary rock' },
      { num: 2, clue: 'Arcade coin' },
      { num: 3, clue: 'Like helium, chemically' },
      { num: 4, clue: 'Monthly payment to a landlord' },
      { num: 5, clue: 'Take a ___ at (attempt)' },
    ],
  },

  {
    grid: ['##OWE', '#FREE', 'LABEL', 'ACID#', 'YET##'],
    cluesAcross: [
      { num: 1, clue: 'Be in debt for' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Sticker with info' },
      { num: 6, clue: 'Sour chemical, or lemon juice' },
      { num: 7, clue: 'Up to now' },
    ],
    cluesDown: [
      { num: 1, clue: 'Path around a planet' },
      { num: 2, clue: 'Garden intruder' },
      { num: 3, clue: 'Slippery fish' },
      { num: 4, clue: 'Head\'s front' },
      { num: 5, clue: 'Set down flat' },
    ],
  },
  {
    grid: ['##HAS', '#BORE', 'BRUTE', 'EASY#', 'DYE##'],
    cluesAcross: [
      { num: 1, clue: 'Possesses, third person' },
      { num: 4, clue: 'Dull person' },
      { num: 5, clue: 'Savage creature' },
      { num: 6, clue: 'Not hard' },
      { num: 7, clue: 'Fabric colorant' },
    ],
    cluesDown: [
      { num: 1, clue: 'Where you live' },
      { num: 2, clue: 'Pretentiously artistic' },
      { num: 3, clue: 'Perceive with the eyes' },
      { num: 4, clue: 'Donkey\'s cry' },
      { num: 5, clue: 'Where you sleep' },
    ],
  },
  {
    grid: ['##DOT', '#BEAR', 'NASTY', 'ASKS#', 'YES##'],
    cluesAcross: [
      { num: 1, clue: 'Small round mark' },
      { num: 4, clue: 'Hibernating animal' },
      { num: 5, clue: 'Unpleasant' },
      { num: 6, clue: 'Poses questions' },
      { num: 7, clue: 'Affirmative' },
    ],
    cluesDown: [
      { num: 1, clue: 'Classroom furniture, plural' },
      { num: 2, clue: 'Oatmeal source' },
      { num: 3, clue: 'Attempt' },
      { num: 4, clue: 'Foundation, or home plate' },
      { num: 5, clue: 'A no vote' },
    ],
  },
  {
    grid: ['##LID', '#CARE', 'CABIN', 'USES#', 'EEL##'],
    cluesAcross: [
      { num: 1, clue: 'Jar’s cap' },
      { num: 4, clue: 'Concern' },
      { num: 5, clue: 'Rustic wooden house' },
      { num: 6, clue: 'Puts to work' },
      { num: 7, clue: 'Slippery fish' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sticker with info' },
      { num: 2, clue: 'Colored part of the eye' },
      { num: 3, clue: 'Cozy family room' },
      { num: 4, clue: 'Container, or a legal matter' },
      { num: 5, clue: 'Signal to start' },
    ],
  },
  {
    grid: ['##CUR', '#ERGO', 'BUILD', 'ARMY#', 'TOE##'],
    cluesAcross: [
      { num: 1, clue: 'Mongrel dog' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Construct' },
      { num: 6, clue: 'Marching military force' },
      { num: 7, clue: 'Foot digit' },
    ],
    cluesDown: [
      { num: 1, clue: 'Illegal act' },
      { num: 2, clue: 'Not pretty' },
      { num: 3, clue: 'Fishing pole' },
      { num: 4, clue: 'European currency' },
      { num: 5, clue: 'Baseball swinger, or a cave dweller' },
    ],
  },
  {
    grid: ['##CUE', '#CASE', 'LABEL', 'AVID#', 'DEN##'],
    cluesAcross: [
      { num: 1, clue: 'Signal to start' },
      { num: 4, clue: 'Container, or a legal matter' },
      { num: 5, clue: 'Sticker with info' },
      { num: 6, clue: 'Very enthusiastic' },
      { num: 7, clue: 'Cozy family room' },
    ],
    cluesDown: [
      { num: 1, clue: 'Rustic wooden house' },
      { num: 2, clue: 'Not new' },
      { num: 3, clue: 'Slippery fish' },
      { num: 4, clue: 'Underground hollow' },
      { num: 5, clue: 'Young boy' },
    ],
  },
  {
    grid: ['##LAD', '#BARE', 'CABIN', 'USED#', 'EEL##'],
    cluesAcross: [
      { num: 1, clue: 'Young boy' },
      { num: 4, clue: 'Uncovered' },
      { num: 5, clue: 'Rustic wooden house' },
      { num: 6, clue: 'Not new' },
      { num: 7, clue: 'Slippery fish' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sticker with info' },
      { num: 2, clue: 'Very dry' },
      { num: 3, clue: 'Cozy family room' },
      { num: 4, clue: 'Foundation, or home plate' },
      { num: 5, clue: 'Signal to start' },
    ],
  },
  {
    grid: ['##AWE', '#GRAY', 'ALIVE', 'DOSE#', 'OWE##'],
    cluesAcross: [
      { num: 1, clue: 'Wonder and amazement' },
      { num: 4, clue: 'Between black and white' },
      { num: 5, clue: 'Not dead' },
      { num: 6, clue: 'Amount of medicine' },
      { num: 7, clue: 'Be in debt for' },
    ],
    cluesDown: [
      { num: 1, clue: 'Come up' },
      { num: 2, clue: 'Ocean roller' },
      { num: 3, clue: 'Seeing organ' },
      { num: 4, clue: 'Soft light' },
      { num: 5, clue: 'Fuss' },
    ],
  },
  {
    grid: ['##HAY', '#FAME', 'CABIN', 'ARID#', 'NET##'],
    cluesAcross: [
      { num: 1, clue: 'Barn feed' },
      { num: 4, clue: 'Widespread renown' },
      { num: 5, clue: 'Rustic wooden house' },
      { num: 6, clue: 'Very dry' },
      { num: 7, clue: 'Basketball hoop\'s mesh' },
    ],
    cluesDown: [
      { num: 1, clue: 'Regular routine' },
      { num: 2, clue: 'In the middle of' },
      { num: 3, clue: 'Strong craving, or Japanese currency' },
      { num: 4, clue: 'Bus ticket price' },
      { num: 5, clue: 'Soda container' },
    ],
  },
  {
    grid: ['##ADO', '#GRIP', 'FLEET', 'AUNT#', 'TEA##'],
    cluesAcross: [
      { num: 1, clue: 'Fuss' },
      { num: 4, clue: 'Firm hold' },
      { num: 5, clue: 'Group of ships' },
      { num: 6, clue: 'Parent\'s sister' },
      { num: 7, clue: 'Afternoon brew' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sports venue' },
      { num: 2, clue: 'Eating plan' },
      { num: 3, clue: 'Choose to' },
      { num: 4, clue: 'Sticky bonder' },
      { num: 5, clue: 'Not thin' },
    ],
  },
  {
    grid: ['##LAY', '#BALE', 'BURST', 'ERGO#', 'DYE##'],
    cluesAcross: [
      { num: 1, clue: 'Set down flat' },
      { num: 4, clue: 'Hay bundle' },
      { num: 5, clue: 'Sudden explosion' },
      { num: 6, clue: 'Therefore, formally' },
      { num: 7, clue: 'Fabric colorant' },
    ],
    cluesDown: [
      { num: 1, clue: 'Big' },
      { num: 2, clue: 'In addition' },
      { num: 3, clue: 'Up to now' },
      { num: 4, clue: 'Put in the ground' },
      { num: 5, clue: 'Where you sleep' },
    ],
  },
  {
    grid: ['##HER', '#CODE', 'FLUID', 'EAST#', 'EYE##'],
    cluesAcross: [
      { num: 1, clue: 'That woman, objectively' },
      { num: 4, clue: 'Secret cipher' },
      { num: 5, clue: 'Liquid' },
      { num: 6, clue: 'Sunrise direction' },
      { num: 7, clue: 'Seeing organ' },
    ],
    cluesDown: [
      { num: 1, clue: 'Where you live' },
      { num: 2, clue: 'Revise text' },
      { num: 3, clue: 'Fire-engine color' },
      { num: 4, clue: 'Pottery material' },
      { num: 5, clue: 'Charge for a service' },
    ],
  },
  {
    grid: ['##BUY', '#CURE', 'ALIGN', 'GALE#', 'END##'],
    cluesAcross: [
      { num: 1, clue: 'Purchase' },
      { num: 4, clue: 'Medical fix' },
      { num: 5, clue: 'Line up' },
      { num: 6, clue: 'Strong wind' },
      { num: 7, clue: 'Finish' },
    ],
    cluesDown: [
      { num: 1, clue: 'Construct' },
      { num: 2, clue: 'Strong impulse' },
      { num: 3, clue: 'Strong craving, or Japanese currency' },
      { num: 4, clue: 'Extended family group' },
      { num: 5, clue: 'How old you are' },
    ],
  },
  {
    grid: ['##BAY', '#BORE', 'DRAIN', 'YARD#', 'END##'],
    cluesAcross: [
      { num: 1, clue: 'Coastal inlet' },
      { num: 4, clue: 'Dull person' },
      { num: 5, clue: 'Sink outlet' },
      { num: 6, clue: 'Backyard measure, 3 feet' },
      { num: 7, clue: 'Finish' },
    ],
    cluesDown: [
      { num: 1, clue: 'Classroom writing surface' },
      { num: 2, clue: 'Very dry' },
      { num: 3, clue: 'Strong craving, or Japanese currency' },
      { num: 4, clue: 'Cereal fiber' },
      { num: 5, clue: 'Fabric colorant' },
    ],
  },
  {
    grid: ['##CAB', '#FAME', 'HABIT', 'ARID#', 'MEN##'],
    cluesAcross: [
      { num: 1, clue: 'Taxi' },
      { num: 4, clue: 'Widespread renown' },
      { num: 5, clue: 'Regular routine' },
      { num: 6, clue: 'Very dry' },
      { num: 7, clue: 'Adult males' },
    ],
    cluesDown: [
      { num: 1, clue: 'Rustic wooden house' },
      { num: 2, clue: 'In the middle of' },
      { num: 3, clue: 'Wager' },
      { num: 4, clue: 'Bus ticket price' },
      { num: 5, clue: 'Deli meat, or an overactor' },
    ],
  },
  {
    grid: ['##FIN', '#FARE', 'FRUIT', 'EELS#', 'WET##'],
    cluesAcross: [
      { num: 1, clue: 'Fish\'s paddle' },
      { num: 4, clue: 'Bus ticket price' },
      { num: 5, clue: 'Apple or banana' },
      { num: 6, clue: 'Slippery fish' },
      { num: 7, clue: 'Not dry' },
    ],
    cluesDown: [
      { num: 1, clue: 'Blame' },
      { num: 2, clue: 'Colored part of the eye' },
      { num: 3, clue: 'Basketball hoop\'s mesh' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Not many' },
    ],
  },
  {
    grid: ['##SUM', '#ELSE', 'GREEN', 'AGED#', 'LOP##'],
    cluesAcross: [
      { num: 1, clue: 'Total' },
      { num: 4, clue: 'Otherwise' },
      { num: 5, clue: 'Grass\'s color' },
      { num: 6, clue: 'Grown old' },
      { num: 7, clue: 'Chop off' },
    ],
    cluesDown: [
      { num: 1, clue: 'Nighttime rest' },
      { num: 2, clue: 'Not new' },
      { num: 3, clue: 'Adult males' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Girl, informally' },
    ],
  },
  {
    grid: ['SOD##', 'OVEN#', 'BACON', '#LATE', '##YET'],
    cluesAcross: [
      { num: 1, clue: 'Turf' },
      { num: 4, clue: 'Bakes the bread' },
      { num: 6, clue: 'Breakfast strip' },
      { num: 8, clue: 'Not on time' },
      { num: 9, clue: 'Up to now' },
    ],
    cluesDown: [
      { num: 1, clue: 'Cry loudly' },
      { num: 2, clue: 'Egg shape' },
      { num: 3, clue: 'Rot' },
      { num: 5, clue: 'Quick reminder' },
      { num: 7, clue: 'Basketball hoop\'s mesh' },
    ],
  },
  {
    grid: ['ODD##', 'NEED#', 'SALAD', '#LATE', '##YEN'],
    cluesAcross: [
      { num: 1, clue: 'Not even' },
      { num: 4, clue: 'Require' },
      { num: 6, clue: 'Leafy bowl dish' },
      { num: 8, clue: 'Not on time' },
      { num: 9, clue: 'Strong craving, or Japanese currency' },
    ],
    cluesDown: [
      { num: 1, clue: 'Add-ons, informally' },
      { num: 2, clue: 'Bargain' },
      { num: 3, clue: 'Postpone' },
      { num: 5, clue: 'Sweet dried fruit, or a night out' },
      { num: 7, clue: 'Cozy family room' },
    ],
  },
  {
    grid: ['EGG##', 'LORD#', 'FLOOD', '#DUNE', '##PEW'],
    cluesAcross: [
      { num: 1, clue: 'Breakfast oval' },
      { num: 4, clue: 'Manor\'s master' },
      { num: 6, clue: 'Overflowing water' },
      { num: 8, clue: 'Desert sand hill' },
      { num: 9, clue: 'Church bench' },
    ],
    cluesDown: [
      { num: 1, clue: 'Santa’s helper' },
      { num: 2, clue: 'Precious yellow metal' },
      { num: 3, clue: 'Team or cluster' },
      { num: 5, clue: 'Finished' },
      { num: 7, clue: 'Morning grass moisture' },
    ],
  },
  {
    grid: ['##EVE', '#GRIN', 'BRAND', 'EASE#', 'DYE##'],
    cluesAcross: [
      { num: 1, clue: 'Night before' },
      { num: 4, clue: 'Wide smile' },
      { num: 5, clue: 'Company name' },
      { num: 6, clue: 'Comfort' },
      { num: 7, clue: 'Fabric colorant' },
    ],
    cluesDown: [
      { num: 1, clue: 'Rub out' },
      { num: 2, clue: 'Grapes grow on it' },
      { num: 3, clue: 'Finish' },
      { num: 4, clue: 'Between black and white' },
      { num: 5, clue: 'Where you sleep' },
    ],
  },
  {
    grid: ['OLD##', 'FORM#', 'FRAIL', '#DICE', '##NET'],
    cluesAcross: [
      { num: 1, clue: 'Not young' },
      { num: 4, clue: 'Shape, or a document' },
      { num: 6, clue: 'Physically weak' },
      { num: 8, clue: 'Board-game cubes' },
      { num: 9, clue: 'Basketball hoop\'s mesh' },
    ],
    cluesDown: [
      { num: 1, clue: 'Not on' },
      { num: 2, clue: 'Manor\'s master' },
      { num: 3, clue: 'Sink outlet' },
      { num: 5, clue: 'Plural of mouse' },
      { num: 7, clue: 'Allow' },
    ],
  },
  {
    grid: ['##PAY', '#BASE', 'DESKS', 'OATS#', 'ERA##'],
    cluesAcross: [
      { num: 1, clue: 'Compensate' },
      { num: 4, clue: 'Foundation, or home plate' },
      { num: 5, clue: 'Classroom furniture, plural' },
      { num: 6, clue: 'Oatmeal source' },
      { num: 7, clue: 'Historical span' },
    ],
    cluesDown: [
      { num: 1, clue: 'Spaghetti\'s category' },
      { num: 2, clue: 'Poses questions' },
      { num: 3, clue: 'Affirmative' },
      { num: 4, clue: 'Hibernating animal' },
      { num: 5, clue: 'Female deer' },
    ],
  },
  {
    grid: ['##AGE', '#FRAY', 'ALIVE', 'DOSE#', 'OWE##'],
    cluesAcross: [
      { num: 1, clue: 'How old you are' },
      { num: 4, clue: 'Unravel, or a brawl' },
      { num: 5, clue: 'Not dead' },
      { num: 6, clue: 'Amount of medicine' },
      { num: 7, clue: 'Be in debt for' },
    ],
    cluesDown: [
      { num: 1, clue: 'Come up' },
      { num: 2, clue: 'Handed over, past tense' },
      { num: 3, clue: 'Seeing organ' },
      { num: 4, clue: 'Steady movement' },
      { num: 5, clue: 'Fuss' },
    ],
  },
  {
    grid: ['ERR##', 'LOAF#', 'MODEL', '#FINE', '##ODD'],
    cluesAcross: [
      { num: 1, clue: 'Make a mistake' },
      { num: 4, clue: 'Bread shape' },
      { num: 6, clue: 'Small-scale replica' },
      { num: 8, clue: 'Okay, or a penalty payment' },
      { num: 9, clue: 'Not even' },
    ],
    cluesDown: [
      { num: 1, clue: 'Shade tree' },
      { num: 2, clue: 'Top of a house' },
      { num: 3, clue: 'Broadcasts music' },
      { num: 5, clue: 'Ward off' },
      { num: 7, clue: 'Guided' },
    ],
  },
  {
    grid: ['##BUD', '#CURE', 'ALIGN', 'GALE#', 'END##'],
    cluesAcross: [
      { num: 1, clue: 'Flower before bloom' },
      { num: 4, clue: 'Medical fix' },
      { num: 5, clue: 'Line up' },
      { num: 6, clue: 'Strong wind' },
      { num: 7, clue: 'Finish' },
    ],
    cluesDown: [
      { num: 1, clue: 'Construct' },
      { num: 2, clue: 'Strong impulse' },
      { num: 3, clue: 'Cozy family room' },
      { num: 4, clue: 'Extended family group' },
      { num: 5, clue: 'How old you are' },
    ],
  },
  {
    grid: ['##OFF', '#FREE', 'FABLE', 'EMIT#', 'WET##'],
    cluesAcross: [
      { num: 1, clue: 'Not on' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Fictional story with a moral' },
      { num: 6, clue: 'Give off' },
      { num: 7, clue: 'Not dry' },
    ],
    cluesDown: [
      { num: 1, clue: 'Path around a planet' },
      { num: 2, clue: 'Sensed, or a soft fabric' },
      { num: 3, clue: 'Charge for a service' },
      { num: 4, clue: 'Widespread renown' },
      { num: 5, clue: 'Not many' },
    ],
  },
  {
    grid: ['OFF##', 'ROAD#', 'BACON', '#MENU', '##DEN'],
    cluesAcross: [
      { num: 1, clue: 'Not on' },
      { num: 4, clue: 'Paved route' },
      { num: 6, clue: 'Breakfast strip' },
      { num: 8, clue: 'Restaurant\'s list' },
      { num: 9, clue: 'Cozy family room' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sphere' },
      { num: 2, clue: 'Bubbly froth' },
      { num: 3, clue: 'Confronted' },
      { num: 5, clue: 'Finished' },
      { num: 7, clue: 'Convent resident' },
    ],
  },
  {
    grid: ['##HAM', '#FACE', 'CABIN', 'AMID#', 'NET##'],
    cluesAcross: [
      { num: 1, clue: 'Deli meat, or an overactor' },
      { num: 4, clue: 'Head\'s front' },
      { num: 5, clue: 'Rustic wooden house' },
      { num: 6, clue: 'In the middle of' },
      { num: 7, clue: 'Basketball hoop\'s mesh' },
    ],
    cluesDown: [
      { num: 1, clue: 'Regular routine' },
      { num: 2, clue: 'Sour chemical, or lemon juice' },
      { num: 3, clue: 'Adult males' },
      { num: 4, clue: 'Widespread renown' },
      { num: 5, clue: 'Soda container' },
    ],
  },
  {
    grid: ['##HAG', '#CAGE', 'LABEL', 'ARID#', 'BET##'],
    cluesAcross: [
      { num: 1, clue: 'Old crone' },
      { num: 4, clue: 'Bird enclosure' },
      { num: 5, clue: 'Sticker with info' },
      { num: 6, clue: 'Very dry' },
      { num: 7, clue: 'Wager' },
    ],
    cluesDown: [
      { num: 1, clue: 'Regular routine' },
      { num: 2, clue: 'Grown old' },
      { num: 3, clue: 'Hair-styling goop' },
      { num: 4, clue: 'Concern' },
      { num: 5, clue: 'Science classroom' },
    ],
  },
  {
    grid: ['##FEW', '#FAME', 'ORBIT', 'FELT#', 'FEE##'],
    cluesAcross: [
      { num: 1, clue: 'Not many' },
      { num: 4, clue: 'Widespread renown' },
      { num: 5, clue: 'Path around a planet' },
      { num: 6, clue: 'Sensed, or a soft fabric' },
      { num: 7, clue: 'Charge for a service' },
    ],
    cluesDown: [
      { num: 1, clue: 'Fictional story with a moral' },
      { num: 2, clue: 'Give off' },
      { num: 3, clue: 'Not dry' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Not on' },
    ],
  },
  {
    grid: ['ELF##', 'BORN#', 'BRAIN', '#DICE', '##LET'],
    cluesAcross: [
      { num: 1, clue: 'Santa’s helper' },
      { num: 4, clue: 'Brought into life' },
      { num: 6, clue: 'Thinking organ' },
      { num: 8, clue: 'Board-game cubes' },
      { num: 9, clue: 'Allow' },
    ],
    cluesDown: [
      { num: 1, clue: 'Tide\'s outward flow' },
      { num: 2, clue: 'Manor\'s master' },
      { num: 3, clue: 'Physically weak' },
      { num: 5, clue: 'Pleasant' },
      { num: 7, clue: 'Basketball hoop\'s mesh' },
    ],
  },
  {
    grid: ['##SUP', '#ELSE', 'GREEN', 'AGED#', 'LOP##'],
    cluesAcross: [
      { num: 1, clue: 'Have supper' },
      { num: 4, clue: 'Otherwise' },
      { num: 5, clue: 'Grass\'s color' },
      { num: 6, clue: 'Grown old' },
      { num: 7, clue: 'Chop off' },
    ],
    cluesDown: [
      { num: 1, clue: 'Nighttime rest' },
      { num: 2, clue: 'Not new' },
      { num: 3, clue: 'Writing tool' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Girl, informally' },
    ],
  },
  {
    grid: ['##LAP', '#CAVE', 'CABIN', 'USED#', 'EEL##'],
    cluesAcross: [
      { num: 1, clue: 'One trip around a track' },
      { num: 4, clue: 'Underground hollow' },
      { num: 5, clue: 'Rustic wooden house' },
      { num: 6, clue: 'Not new' },
      { num: 7, clue: 'Slippery fish' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sticker with info' },
      { num: 2, clue: 'Very enthusiastic' },
      { num: 3, clue: 'Writing tool' },
      { num: 4, clue: 'Container, or a legal matter' },
      { num: 5, clue: 'Signal to start' },
    ],
  },
  {
    grid: ['##NAY', '#BASE', 'DESKS', 'OATS#', 'TRY##'],
    cluesAcross: [
      { num: 1, clue: 'A no vote' },
      { num: 4, clue: 'Foundation, or home plate' },
      { num: 5, clue: 'Classroom furniture, plural' },
      { num: 6, clue: 'Oatmeal source' },
      { num: 7, clue: 'Attempt' },
    ],
    cluesDown: [
      { num: 1, clue: 'Unpleasant' },
      { num: 2, clue: 'Poses questions' },
      { num: 3, clue: 'Affirmative' },
      { num: 4, clue: 'Hibernating animal' },
      { num: 5, clue: 'Small round mark' },
    ],
  },
  {
    grid: ['##GAL', '#ERGO', 'SLEEP', 'USED#', 'MEN##'],
    cluesAcross: [
      { num: 1, clue: 'Girl, informally' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Nighttime rest' },
      { num: 6, clue: 'Not new' },
      { num: 7, clue: 'Adult males' },
    ],
    cluesDown: [
      { num: 1, clue: 'Grass\'s color' },
      { num: 2, clue: 'Grown old' },
      { num: 3, clue: 'Chop off' },
      { num: 4, clue: 'Otherwise' },
      { num: 5, clue: 'Total' },
    ],
  },
  {
    grid: ['##HIS', '#CARE', 'ELBOW', 'RAIN#', 'ANT##'],
    cluesAcross: [
      { num: 1, clue: 'Belonging to that man' },
      { num: 4, clue: 'Concern' },
      { num: 5, clue: 'Funny bone’s joint' },
      { num: 6, clue: 'Falls from clouds' },
      { num: 7, clue: 'Picnic pest' },
    ],
    cluesDown: [
      { num: 1, clue: 'Regular routine' },
      { num: 2, clue: 'Metal, or a wrinkle remover' },
      { num: 3, clue: 'Stitch fabric' },
      { num: 4, clue: 'Extended family group' },
      { num: 5, clue: 'Historical span' },
    ],
  },
  {
    grid: ['##HUB', '#ROSE', 'DATED', 'ICED#', 'GEL##'],
    cluesAcross: [
      { num: 1, clue: 'Central point' },
      { num: 4, clue: 'Valentine\'s flower' },
      { num: 5, clue: 'Old-fashioned' },
      { num: 6, clue: 'Chilled, as tea' },
      { num: 7, clue: 'Hair-styling goop' },
    ],
    cluesDown: [
      { num: 1, clue: 'Overnight stay spot' },
      { num: 2, clue: 'Not new' },
      { num: 3, clue: 'Where you sleep' },
      { num: 4, clue: 'Speed contest' },
      { num: 5, clue: 'Excavate' },
    ],
  },
  {
    grid: ['##HEM', '#DOME', 'FRUIT', 'EAST#', 'EWE##'],
    cluesAcross: [
      { num: 1, clue: 'Skirt\'s folded edge' },
      { num: 4, clue: 'Rounded roof' },
      { num: 5, clue: 'Apple or banana' },
      { num: 6, clue: 'Sunrise direction' },
      { num: 7, clue: 'Female sheep' },
    ],
    cluesDown: [
      { num: 1, clue: 'Where you live' },
      { num: 2, clue: 'Give off' },
      { num: 3, clue: 'Encountered' },
      { num: 4, clue: 'Sketch, or a tie score' },
      { num: 5, clue: 'Charge for a service' },
    ],
  },
  {
    grid: ['##CAP', '#GATE', 'ARROW', 'DOOM#', 'OWL##'],
    cluesAcross: [
      { num: 1, clue: 'Baseball hat' },
      { num: 4, clue: 'Fence opening' },
      { num: 5, clue: 'Bow’s projectile' },
      { num: 6, clue: 'Grim fate' },
      { num: 7, clue: 'Nocturnal bird' },
    ],
    cluesDown: [
      { num: 1, clue: 'Christmas song' },
      { num: 2, clue: 'Tiny building block of matter' },
      { num: 3, clue: 'Church bench' },
      { num: 4, clue: 'Get bigger' },
      { num: 5, clue: 'Fuss' },
    ],
  },
  {
    grid: ['EBB##', 'LORD#', 'FRAIL', '#NICE', '##NET'],
    cluesAcross: [
      { num: 1, clue: 'Tide\'s outward flow' },
      { num: 4, clue: 'Manor\'s master' },
      { num: 6, clue: 'Physically weak' },
      { num: 8, clue: 'Pleasant' },
      { num: 9, clue: 'Basketball hoop\'s mesh' },
    ],
    cluesDown: [
      { num: 1, clue: 'Santa’s helper' },
      { num: 2, clue: 'Brought into life' },
      { num: 3, clue: 'Thinking organ' },
      { num: 5, clue: 'Board-game cubes' },
      { num: 7, clue: 'Allow' },
    ],
  },
  {
    grid: ['LAG##', 'ABLY#', 'BLOOM', '#ERGO', '##YAP'],
    cluesAcross: [
      { num: 1, clue: 'Fall behind' },
      { num: 4, clue: 'Skillfully' },
      { num: 6, clue: 'Flower opening' },
      { num: 8, clue: 'Therefore, formally' },
      { num: 9, clue: 'Small dog\'s bark' },
    ],
    cluesDown: [
      { num: 1, clue: 'Science classroom' },
      { num: 2, clue: 'Capable' },
      { num: 3, clue: 'Great honor' },
      { num: 5, clue: 'Downward dog practice' },
      { num: 7, clue: 'Floor cleaner' },
    ],
  },
  {
    grid: ['##MEN', '#DOME', 'FRUIT', 'EAST#', 'EWE##'],
    cluesAcross: [
      { num: 1, clue: 'Adult males' },
      { num: 4, clue: 'Rounded roof' },
      { num: 5, clue: 'Apple or banana' },
      { num: 6, clue: 'Sunrise direction' },
      { num: 7, clue: 'Female sheep' },
    ],
    cluesDown: [
      { num: 1, clue: 'Computer clicker, or a small rodent' },
      { num: 2, clue: 'Give off' },
      { num: 3, clue: 'Basketball hoop\'s mesh' },
      { num: 4, clue: 'Sketch, or a tie score' },
      { num: 5, clue: 'Charge for a service' },
    ],
  },
  {
    grid: ['##LAB', '#FARE', 'ORBIT', 'NEED#', 'EEL##'],
    cluesAcross: [
      { num: 1, clue: 'Science classroom' },
      { num: 4, clue: 'Bus ticket price' },
      { num: 5, clue: 'Path around a planet' },
      { num: 6, clue: 'Require' },
      { num: 7, clue: 'Slippery fish' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sticker with info' },
      { num: 2, clue: 'Very dry' },
      { num: 3, clue: 'Wager' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Loneliest number' },
    ],
  },
  {
    grid: ['LAB##', 'ABLE#', 'GLORY', '#YOGA', '##MOP'],
    cluesAcross: [
      { num: 1, clue: 'Science classroom' },
      { num: 4, clue: 'Capable' },
      { num: 6, clue: 'Great honor' },
      { num: 8, clue: 'Downward dog practice' },
      { num: 9, clue: 'Floor cleaner' },
    ],
    cluesDown: [
      { num: 1, clue: 'Fall behind' },
      { num: 2, clue: 'Skillfully' },
      { num: 3, clue: 'Flower opening' },
      { num: 5, clue: 'Therefore, formally' },
      { num: 7, clue: 'Small dog\'s bark' },
    ],
  },
  {
    grid: ['##FAN', '#ERGO', 'FLEET', 'USES#', 'RED##'],
    cluesAcross: [
      { num: 1, clue: 'Cooling device' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Group of ships' },
      { num: 6, clue: 'Puts to work' },
      { num: 7, clue: 'Fire-engine color' },
    ],
    cluesDown: [
      { num: 1, clue: 'Released' },
      { num: 2, clue: 'Grows old, or eras' },
      { num: 3, clue: 'Negation word' },
      { num: 4, clue: 'Otherwise' },
      { num: 5, clue: 'Coat on a cat' },
    ],
  },
  {
    grid: ['##ERA', '#CLAN', 'HABIT', 'IRON#', 'PEW##'],
    cluesAcross: [
      { num: 1, clue: 'Historical span' },
      { num: 4, clue: 'Extended family group' },
      { num: 5, clue: 'Regular routine' },
      { num: 6, clue: 'Metal, or a wrinkle remover' },
      { num: 7, clue: 'Church bench' },
    ],
    cluesDown: [
      { num: 1, clue: 'Funny bone’s joint' },
      { num: 2, clue: 'Falls from clouds' },
      { num: 3, clue: 'Picnic pest' },
      { num: 4, clue: 'Concern' },
      { num: 5, clue: 'Dance move joint' },
    ],
  },
  {
    grid: ['ERA##', 'BOLT#', 'BOARD', '#FREE', '##MEN'],
    cluesAcross: [
      { num: 1, clue: 'Historical span' },
      { num: 4, clue: 'Nut\'s partner' },
      { num: 6, clue: 'Classroom writing surface' },
      { num: 8, clue: 'No cost' },
      { num: 9, clue: 'Adult males' },
    ],
    cluesDown: [
      { num: 1, clue: 'Tide\'s outward flow' },
      { num: 2, clue: 'Top of a house' },
      { num: 3, clue: 'Wake-up sound' },
      { num: 5, clue: 'Has leaves and bark' },
      { num: 7, clue: 'Cozy family room' },
    ],
  },
  {
    grid: ['##HIP', '#CARE', 'ELBOW', 'RAIN#', 'ANT##'],
    cluesAcross: [
      { num: 1, clue: 'Dance move joint' },
      { num: 4, clue: 'Concern' },
      { num: 5, clue: 'Funny bone’s joint' },
      { num: 6, clue: 'Falls from clouds' },
      { num: 7, clue: 'Picnic pest' },
    ],
    cluesDown: [
      { num: 1, clue: 'Regular routine' },
      { num: 2, clue: 'Metal, or a wrinkle remover' },
      { num: 3, clue: 'Church bench' },
      { num: 4, clue: 'Extended family group' },
      { num: 5, clue: 'Historical span' },
    ],
  },
  {
    grid: ['##FAD', '#ERGO', 'FLEET', 'USES#', 'RED##'],
    cluesAcross: [
      { num: 1, clue: 'Passing trend' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Group of ships' },
      { num: 6, clue: 'Puts to work' },
      { num: 7, clue: 'Fire-engine color' },
    ],
    cluesDown: [
      { num: 1, clue: 'Released' },
      { num: 2, clue: 'Grows old, or eras' },
      { num: 3, clue: 'Small round mark' },
      { num: 4, clue: 'Otherwise' },
      { num: 5, clue: 'Coat on a cat' },
    ],
  },
  {
    grid: ['##BUS', '#FINE', 'ORBIT', 'FELT#', 'FEE##'],
    cluesAcross: [
      { num: 1, clue: 'School ride' },
      { num: 4, clue: 'Okay, or a penalty payment' },
      { num: 5, clue: 'Path around a planet' },
      { num: 6, clue: 'Sensed, or a soft fabric' },
      { num: 7, clue: 'Charge for a service' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sacred Christian book' },
      { num: 2, clue: 'Single measuring piece' },
      { num: 3, clue: 'Matching group' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Not on' },
    ],
  },
  {
    grid: ['##CUP', '#ERGO', 'BUILD', 'ARMY#', 'TOE##'],
    cluesAcross: [
      { num: 1, clue: 'Coffee holder' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Construct' },
      { num: 6, clue: 'Marching military force' },
      { num: 7, clue: 'Foot digit' },
    ],
    cluesDown: [
      { num: 1, clue: 'Illegal act' },
      { num: 2, clue: 'Not pretty' },
      { num: 3, clue: 'Pea container' },
      { num: 4, clue: 'European currency' },
      { num: 5, clue: 'Baseball swinger, or a cave dweller' },
    ],
  },
  {
    grid: ['##HID', '#CARE', 'ELBOW', 'RAIN#', 'ANT##'],
    cluesAcross: [
      { num: 1, clue: 'Concealed' },
      { num: 4, clue: 'Concern' },
      { num: 5, clue: 'Funny bone’s joint' },
      { num: 6, clue: 'Falls from clouds' },
      { num: 7, clue: 'Picnic pest' },
    ],
    cluesDown: [
      { num: 1, clue: 'Regular routine' },
      { num: 2, clue: 'Metal, or a wrinkle remover' },
      { num: 3, clue: 'Morning grass moisture' },
      { num: 4, clue: 'Extended family group' },
      { num: 5, clue: 'Historical span' },
    ],
  },
  {
    grid: ['##HEN', '#COME', 'FRUIT', 'EAST#', 'EWE##'],
    cluesAcross: [
      { num: 1, clue: 'Egg layer' },
      { num: 4, clue: 'Arrive' },
      { num: 5, clue: 'Apple or banana' },
      { num: 6, clue: 'Sunrise direction' },
      { num: 7, clue: 'Female sheep' },
    ],
    cluesDown: [
      { num: 1, clue: 'Where you live' },
      { num: 2, clue: 'Give off' },
      { num: 3, clue: 'Basketball hoop\'s mesh' },
      { num: 4, clue: 'A bird\'s crop' },
      { num: 5, clue: 'Charge for a service' },
    ],
  },
  {
    grid: ['##ODE', '#FREE', 'LABEL', 'AMID#', 'YET##'],
    cluesAcross: [
      { num: 1, clue: 'Poem of praise' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Sticker with info' },
      { num: 6, clue: 'In the middle of' },
      { num: 7, clue: 'Up to now' },
    ],
    cluesDown: [
      { num: 1, clue: 'Path around a planet' },
      { num: 2, clue: 'Property document' },
      { num: 3, clue: 'Slippery fish' },
      { num: 4, clue: 'Widespread renown' },
      { num: 5, clue: 'Set down flat' },
    ],
  },
  {
    grid: ['##DYE', '#BRAN', 'BOARD', 'ARID#', 'YEN##'],
    cluesAcross: [
      { num: 1, clue: 'Fabric colorant' },
      { num: 4, clue: 'Cereal fiber' },
      { num: 5, clue: 'Classroom writing surface' },
      { num: 6, clue: 'Very dry' },
      { num: 7, clue: 'Strong craving, or Japanese currency' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sink outlet' },
      { num: 2, clue: 'Backyard measure, 3 feet' },
      { num: 3, clue: 'Finish' },
      { num: 4, clue: 'Dull person' },
      { num: 5, clue: 'Coastal inlet' },
    ],
  },
  {
    grid: ['##WHO', '#COIN', 'LOOSE', 'ADDS#', 'YES##'],
    cluesAcross: [
      { num: 1, clue: 'Which person' },
      { num: 4, clue: 'Metal money' },
      { num: 5, clue: 'Not tight' },
      { num: 6, clue: 'Sums up' },
      { num: 7, clue: 'Affirmative' },
    ],
    cluesDown: [
      { num: 1, clue: 'Small forest' },
      { num: 2, clue: 'Snake sound' },
      { num: 3, clue: 'Loneliest number' },
      { num: 4, clue: 'Secret cipher' },
      { num: 5, clue: 'Set down flat' },
    ],
  },
  {
    grid: ['##FEE', '#CLAY', 'CAUSE', 'UNIT#', 'BED##'],
    cluesAcross: [
      { num: 1, clue: 'Charge for a service' },
      { num: 4, clue: 'Pottery material' },
      { num: 5, clue: 'Reason for an effect' },
      { num: 6, clue: 'Single measuring piece' },
      { num: 7, clue: 'Where you sleep' },
    ],
    cluesDown: [
      { num: 1, clue: 'Liquid' },
      { num: 2, clue: 'Sunrise direction' },
      { num: 3, clue: 'Seeing organ' },
      { num: 4, clue: 'Walking aid' },
      { num: 5, clue: 'Baby bear' },
    ],
  },
  {
    grid: ['##DIG', '#RACE', 'HOTEL', 'USED#', 'BED##'],
    cluesAcross: [
      { num: 1, clue: 'Excavate' },
      { num: 4, clue: 'Speed contest' },
      { num: 5, clue: 'Overnight stay spot' },
      { num: 6, clue: 'Not new' },
      { num: 7, clue: 'Where you sleep' },
    ],
    cluesDown: [
      { num: 1, clue: 'Old-fashioned' },
      { num: 2, clue: 'Chilled, as tea' },
      { num: 3, clue: 'Hair-styling goop' },
      { num: 4, clue: 'Valentine\'s flower' },
      { num: 5, clue: 'Central point' },
    ],
  },
  {
    grid: ['##LAM', '#CAVE', 'HABIT', 'AGED#', 'GEL##'],
    cluesAcross: [
      { num: 1, clue: 'On the run' },
      { num: 4, clue: 'Underground hollow' },
      { num: 5, clue: 'Regular routine' },
      { num: 6, clue: 'Grown old' },
      { num: 7, clue: 'Hair-styling goop' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sticker with info' },
      { num: 2, clue: 'Very enthusiastic' },
      { num: 3, clue: 'Encountered' },
      { num: 4, clue: 'Bird enclosure' },
      { num: 5, clue: 'Old crone' },
    ],
  },
  {
    grid: ['ELM##', 'ROOF#', 'RADIO', '#FELL', '##LED'],
    cluesAcross: [
      { num: 1, clue: 'Shade tree' },
      { num: 4, clue: 'Top of a house' },
      { num: 6, clue: 'Broadcasts music' },
      { num: 8, clue: 'Dropped, past tense' },
      { num: 9, clue: 'Guided' },
    ],
    cluesDown: [
      { num: 1, clue: 'Make a mistake' },
      { num: 2, clue: 'Bread shape' },
      { num: 3, clue: 'Small-scale replica' },
      { num: 5, clue: 'Document folder' },
      { num: 7, clue: 'Not young' },
    ],
  },
  {
    grid: ['##BAG', '#COLA', 'GLASS', 'EURO#', 'LED##'],
    cluesAcross: [
      { num: 1, clue: 'Grocery carrier' },
      { num: 4, clue: 'Fizzy soda' },
      { num: 5, clue: 'Drinking vessel, or a window pane' },
      { num: 6, clue: 'European currency' },
      { num: 7, clue: 'Guided' },
    ],
    cluesDown: [
      { num: 1, clue: 'Classroom writing surface' },
      { num: 2, clue: 'In addition' },
      { num: 3, clue: 'Fuel at the pump' },
      { num: 4, clue: 'Crossword hint' },
      { num: 5, clue: 'Hair-styling goop' },
    ],
  },
  {
    grid: ['##GAP', '#ERGO', 'SLEEP', 'USES#', 'PEN##'],
    cluesAcross: [
      { num: 1, clue: 'Empty space between' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Nighttime rest' },
      { num: 6, clue: 'Puts to work' },
      { num: 7, clue: 'Writing tool' },
    ],
    cluesDown: [
      { num: 1, clue: 'Grass\'s color' },
      { num: 2, clue: 'Grows old, or eras' },
      { num: 3, clue: 'Soda, in some regions' },
      { num: 4, clue: 'Otherwise' },
      { num: 5, clue: 'Have supper' },
    ],
  },
  {
    grid: ['##BED', '#BURY', 'LARGE', 'ALSO#', 'BET##'],
    cluesAcross: [
      { num: 1, clue: 'Where you sleep' },
      { num: 4, clue: 'Put in the ground' },
      { num: 5, clue: 'Big' },
      { num: 6, clue: 'In addition' },
      { num: 7, clue: 'Wager' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sudden explosion' },
      { num: 2, clue: 'Therefore, formally' },
      { num: 3, clue: 'Fabric colorant' },
      { num: 4, clue: 'Hay bundle' },
      { num: 5, clue: 'Science classroom' },
    ],
  },
  {
    grid: ['##FAT', '#ERGO', 'FLEET', 'USED#', 'RED##'],
    cluesAcross: [
      { num: 1, clue: 'Not thin' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Group of ships' },
      { num: 6, clue: 'Not new' },
      { num: 7, clue: 'Fire-engine color' },
    ],
    cluesDown: [
      { num: 1, clue: 'Released' },
      { num: 2, clue: 'Grown old' },
      { num: 3, clue: 'Toddler' },
      { num: 4, clue: 'Otherwise' },
      { num: 5, clue: 'Coat on a cat' },
    ],
  },
  {
    grid: ['SOB##', 'OVAL#', 'DECAY', '#NOTE', '##NET'],
    cluesAcross: [
      { num: 1, clue: 'Cry loudly' },
      { num: 4, clue: 'Egg shape' },
      { num: 6, clue: 'Rot' },
      { num: 8, clue: 'Quick reminder' },
      { num: 9, clue: 'Basketball hoop\'s mesh' },
    ],
    cluesDown: [
      { num: 1, clue: 'Turf' },
      { num: 2, clue: 'Bakes the bread' },
      { num: 3, clue: 'Breakfast strip' },
      { num: 5, clue: 'Not on time' },
      { num: 7, clue: 'Up to now' },
    ],
  },
  {
    grid: ['##EEL', '#FREE', 'FAULT', 'AMPS#', 'NET##'],
    cluesAcross: [
      { num: 1, clue: 'Slippery fish' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Blame' },
      { num: 6, clue: 'Guitar boosters' },
      { num: 7, clue: 'Basketball hoop\'s mesh' },
    ],
    cluesDown: [
      { num: 1, clue: 'Explode, as a volcano' },
      { num: 2, clue: 'Slippery fish' },
      { num: 3, clue: 'Allow' },
      { num: 4, clue: 'Widespread renown' },
      { num: 5, clue: 'Cooling device' },
    ],
  },
  {
    grid: ['##DOE', '#BEAR', 'PASTA', 'ASKS#', 'YES##'],
    cluesAcross: [
      { num: 1, clue: 'Female deer' },
      { num: 4, clue: 'Hibernating animal' },
      { num: 5, clue: 'Spaghetti\'s category' },
      { num: 6, clue: 'Poses questions' },
      { num: 7, clue: 'Affirmative' },
    ],
    cluesDown: [
      { num: 1, clue: 'Classroom furniture, plural' },
      { num: 2, clue: 'Oatmeal source' },
      { num: 3, clue: 'Historical span' },
      { num: 4, clue: 'Foundation, or home plate' },
      { num: 5, clue: 'Compensate' },
    ],
  },
  {
    grid: ['ONS##', 'DEAL#', 'DELAY', '#DATE', '##DEN'],
    cluesAcross: [
      { num: 1, clue: 'Add-ons, informally' },
      { num: 4, clue: 'Bargain' },
      { num: 6, clue: 'Postpone' },
      { num: 8, clue: 'Sweet dried fruit, or a night out' },
      { num: 9, clue: 'Cozy family room' },
    ],
    cluesDown: [
      { num: 1, clue: 'Not even' },
      { num: 2, clue: 'Require' },
      { num: 3, clue: 'Leafy bowl dish' },
      { num: 5, clue: 'Not on time' },
      { num: 7, clue: 'Strong craving, or Japanese currency' },
    ],
  },
  {
    grid: ['##ONE', '#FREE', 'LABEL', 'ACID#', 'MET##'],
    cluesAcross: [
      { num: 1, clue: 'Loneliest number' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Sticker with info' },
      { num: 6, clue: 'Sour chemical, or lemon juice' },
      { num: 7, clue: 'Encountered' },
    ],
    cluesDown: [
      { num: 1, clue: 'Path around a planet' },
      { num: 2, clue: 'Require' },
      { num: 3, clue: 'Slippery fish' },
      { num: 4, clue: 'Head\'s front' },
      { num: 5, clue: 'On the run' },
    ],
  },
  {
    grid: ['##CUB', '#CANE', 'FRUIT', 'EAST#', 'EWE##'],
    cluesAcross: [
      { num: 1, clue: 'Baby bear' },
      { num: 4, clue: 'Walking aid' },
      { num: 5, clue: 'Apple or banana' },
      { num: 6, clue: 'Sunrise direction' },
      { num: 7, clue: 'Female sheep' },
    ],
    cluesDown: [
      { num: 1, clue: 'Reason for an effect' },
      { num: 2, clue: 'Single measuring piece' },
      { num: 3, clue: 'Wager' },
      { num: 4, clue: 'A bird\'s crop' },
      { num: 5, clue: 'Charge for a service' },
    ],
  },
  {
    grid: ['ORB##', 'FOAM#', 'FACED', '#DONE', '##NUN'],
    cluesAcross: [
      { num: 1, clue: 'Sphere' },
      { num: 4, clue: 'Bubbly froth' },
      { num: 6, clue: 'Confronted' },
      { num: 8, clue: 'Finished' },
      { num: 9, clue: 'Convent resident' },
    ],
    cluesDown: [
      { num: 1, clue: 'Not on' },
      { num: 2, clue: 'Paved route' },
      { num: 3, clue: 'Breakfast strip' },
      { num: 5, clue: 'Restaurant\'s list' },
      { num: 7, clue: 'Cozy family room' },
    ],
  },
  {
    grid: ['##GEL', '#CLUE', 'BOARD', 'ALSO#', 'GAS##'],
    cluesAcross: [
      { num: 1, clue: 'Hair-styling goop' },
      { num: 4, clue: 'Crossword hint' },
      { num: 5, clue: 'Classroom writing surface' },
      { num: 6, clue: 'In addition' },
      { num: 7, clue: 'Fuel at the pump' },
    ],
    cluesDown: [
      { num: 1, clue: 'Drinking vessel, or a window pane' },
      { num: 2, clue: 'European currency' },
      { num: 3, clue: 'Guided' },
      { num: 4, clue: 'Fizzy soda' },
      { num: 5, clue: 'Grocery carrier' },
    ],
  },
  {
    grid: ['##LIP', '#BARE', 'CABIN', 'USES#', 'EEL##'],
    cluesAcross: [
      { num: 1, clue: 'Part of a smile' },
      { num: 4, clue: 'Uncovered' },
      { num: 5, clue: 'Rustic wooden house' },
      { num: 6, clue: 'Puts to work' },
      { num: 7, clue: 'Slippery fish' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sticker with info' },
      { num: 2, clue: 'Colored part of the eye' },
      { num: 3, clue: 'Writing tool' },
      { num: 4, clue: 'Foundation, or home plate' },
      { num: 5, clue: 'Signal to start' },
    ],
  },
  {
    grid: ['##HUM', '#DONE', 'FRUIT', 'EAST#', 'EWE##'],
    cluesAcross: [
      { num: 1, clue: 'Quiet tune' },
      { num: 4, clue: 'Finished' },
      { num: 5, clue: 'Apple or banana' },
      { num: 6, clue: 'Sunrise direction' },
      { num: 7, clue: 'Female sheep' },
    ],
    cluesDown: [
      { num: 1, clue: 'Where you live' },
      { num: 2, clue: 'Single measuring piece' },
      { num: 3, clue: 'Encountered' },
      { num: 4, clue: 'Sketch, or a tie score' },
      { num: 5, clue: 'Charge for a service' },
    ],
  },
  {
    grid: ['##FUR', '#ELSE', 'FREED', 'AGED#', 'NOT##'],
    cluesAcross: [
      { num: 1, clue: 'Coat on a cat' },
      { num: 4, clue: 'Otherwise' },
      { num: 5, clue: 'Released' },
      { num: 6, clue: 'Grown old' },
      { num: 7, clue: 'Negation word' },
    ],
    cluesDown: [
      { num: 1, clue: 'Group of ships' },
      { num: 2, clue: 'Not new' },
      { num: 3, clue: 'Fire-engine color' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Cooling device' },
    ],
  },
  {
    grid: ['##CAN', '#GAVE', 'HABIT', 'AMID#', 'MEN##'],
    cluesAcross: [
      { num: 1, clue: 'Soda container' },
      { num: 4, clue: 'Handed over, past tense' },
      { num: 5, clue: 'Regular routine' },
      { num: 6, clue: 'In the middle of' },
      { num: 7, clue: 'Adult males' },
    ],
    cluesDown: [
      { num: 1, clue: 'Rustic wooden house' },
      { num: 2, clue: 'Very enthusiastic' },
      { num: 3, clue: 'Basketball hoop\'s mesh' },
      { num: 4, clue: 'Board or video pastime' },
      { num: 5, clue: 'Deli meat, or an overactor' },
    ],
  },
  {
    grid: ['##BUN', '#FINE', 'ORBIT', 'FELT#', 'FEE##'],
    cluesAcross: [
      { num: 1, clue: 'Burger bread' },
      { num: 4, clue: 'Okay, or a penalty payment' },
      { num: 5, clue: 'Path around a planet' },
      { num: 6, clue: 'Sensed, or a soft fabric' },
      { num: 7, clue: 'Charge for a service' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sacred Christian book' },
      { num: 2, clue: 'Single measuring piece' },
      { num: 3, clue: 'Basketball hoop\'s mesh' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Not on' },
    ],
  },
  {
    grid: ['##PUP', '#FARE', 'ALIGN', 'DONE#', 'OPT##'],
    cluesAcross: [
      { num: 1, clue: 'Baby dog' },
      { num: 4, clue: 'Bus ticket price' },
      { num: 5, clue: 'Line up' },
      { num: 6, clue: 'Finished' },
      { num: 7, clue: 'Choose to' },
    ],
    cluesDown: [
      { num: 1, clue: 'Wall color' },
      { num: 2, clue: 'Strong impulse' },
      { num: 3, clue: 'Writing tool' },
      { num: 4, clue: 'Failure, or to collapse' },
      { num: 5, clue: 'Fuss' },
    ],
  },
  {
    grid: ['##BAT', '#EURO', 'CRIME', 'UGLY#', 'ROD##'],
    cluesAcross: [
      { num: 1, clue: 'Baseball swinger, or a cave dweller' },
      { num: 4, clue: 'European currency' },
      { num: 5, clue: 'Illegal act' },
      { num: 6, clue: 'Not pretty' },
      { num: 7, clue: 'Fishing pole' },
    ],
    cluesDown: [
      { num: 1, clue: 'Construct' },
      { num: 2, clue: 'Marching military force' },
      { num: 3, clue: 'Foot digit' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Mongrel dog' },
    ],
  },
  {
    grid: ['##OWE', '#FREE', 'LABEL', 'ACID#', 'MET##'],
    cluesAcross: [
      { num: 1, clue: 'Be in debt for' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Sticker with info' },
      { num: 6, clue: 'Sour chemical, or lemon juice' },
      { num: 7, clue: 'Encountered' },
    ],
    cluesDown: [
      { num: 1, clue: 'Path around a planet' },
      { num: 2, clue: 'Garden intruder' },
      { num: 3, clue: 'Slippery fish' },
      { num: 4, clue: 'Head\'s front' },
      { num: 5, clue: 'On the run' },
    ],
  },
  {
    grid: ['##LID', '#BARE', 'CABIN', 'USES#', 'EEL##'],
    cluesAcross: [
      { num: 1, clue: 'Jar’s cap' },
      { num: 4, clue: 'Uncovered' },
      { num: 5, clue: 'Rustic wooden house' },
      { num: 6, clue: 'Puts to work' },
      { num: 7, clue: 'Slippery fish' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sticker with info' },
      { num: 2, clue: 'Colored part of the eye' },
      { num: 3, clue: 'Cozy family room' },
      { num: 4, clue: 'Foundation, or home plate' },
      { num: 5, clue: 'Signal to start' },
    ],
  },
  {
    grid: ['##CUR', '#CANE', 'FLUID', 'EAST#', 'EYE##'],
    cluesAcross: [
      { num: 1, clue: 'Mongrel dog' },
      { num: 4, clue: 'Walking aid' },
      { num: 5, clue: 'Liquid' },
      { num: 6, clue: 'Sunrise direction' },
      { num: 7, clue: 'Seeing organ' },
    ],
    cluesDown: [
      { num: 1, clue: 'Reason for an effect' },
      { num: 2, clue: 'Single measuring piece' },
      { num: 3, clue: 'Fire-engine color' },
      { num: 4, clue: 'Pottery material' },
      { num: 5, clue: 'Charge for a service' },
    ],
  },
  {
    grid: ['##CUE', '#CASE', 'LABEL', 'IRIS#', 'PEN##'],
    cluesAcross: [
      { num: 1, clue: 'Signal to start' },
      { num: 4, clue: 'Container, or a legal matter' },
      { num: 5, clue: 'Sticker with info' },
      { num: 6, clue: 'Colored part of the eye' },
      { num: 7, clue: 'Writing tool' },
    ],
    cluesDown: [
      { num: 1, clue: 'Rustic wooden house' },
      { num: 2, clue: 'Puts to work' },
      { num: 3, clue: 'Slippery fish' },
      { num: 4, clue: 'Concern' },
      { num: 5, clue: 'Part of a smile' },
    ],
  },
  {
    grid: ['##LAD', '#CARE', 'CABIN', 'USED#', 'EEL##'],
    cluesAcross: [
      { num: 1, clue: 'Young boy' },
      { num: 4, clue: 'Concern' },
      { num: 5, clue: 'Rustic wooden house' },
      { num: 6, clue: 'Not new' },
      { num: 7, clue: 'Slippery fish' },
    ],
    cluesDown: [
      { num: 1, clue: 'Sticker with info' },
      { num: 2, clue: 'Very dry' },
      { num: 3, clue: 'Cozy family room' },
      { num: 4, clue: 'Container, or a legal matter' },
      { num: 5, clue: 'Signal to start' },
    ],
  },
  {
    grid: ['##AWE', '#CLAY', 'ARISE', 'DEEP#', 'OWN##'],
    cluesAcross: [
      { num: 1, clue: 'Wonder and amazement' },
      { num: 4, clue: 'Pottery material' },
      { num: 5, clue: 'Come up' },
      { num: 6, clue: 'Not shallow' },
      { num: 7, clue: 'Possess' },
    ],
    cluesDown: [
      { num: 1, clue: 'Space visitor' },
      { num: 2, clue: 'Stinging picnic pest' },
      { num: 3, clue: 'Seeing organ' },
      { num: 4, clue: 'Working team' },
      { num: 5, clue: 'Fuss' },
    ],
  },
  {
    grid: ['##HAY', '#FACE', 'CABIN', 'ARID#', 'NET##'],
    cluesAcross: [
      { num: 1, clue: 'Barn feed' },
      { num: 4, clue: 'Head\'s front' },
      { num: 5, clue: 'Rustic wooden house' },
      { num: 6, clue: 'Very dry' },
      { num: 7, clue: 'Basketball hoop\'s mesh' },
    ],
    cluesDown: [
      { num: 1, clue: 'Regular routine' },
      { num: 2, clue: 'Sour chemical, or lemon juice' },
      { num: 3, clue: 'Strong craving, or Japanese currency' },
      { num: 4, clue: 'Bus ticket price' },
      { num: 5, clue: 'Soda container' },
    ],
  },
  {
    grid: ['##ADO', '#FLOW', 'ARISE', 'GAVE#', 'EYE##'],
    cluesAcross: [
      { num: 1, clue: 'Fuss' },
      { num: 4, clue: 'Steady movement' },
      { num: 5, clue: 'Come up' },
      { num: 6, clue: 'Handed over, past tense' },
      { num: 7, clue: 'Seeing organ' },
    ],
    cluesDown: [
      { num: 1, clue: 'Not dead' },
      { num: 2, clue: 'Amount of medicine' },
      { num: 3, clue: 'Be in debt for' },
      { num: 4, clue: 'Unravel, or a brawl' },
      { num: 5, clue: 'How old you are' },
    ],
  },
  {
    grid: ['##CAB', '#GAVE', 'HABIT', 'AMID#', 'MEN##'],
    cluesAcross: [
      { num: 1, clue: 'Taxi' },
      { num: 4, clue: 'Handed over, past tense' },
      { num: 5, clue: 'Regular routine' },
      { num: 6, clue: 'In the middle of' },
      { num: 7, clue: 'Adult males' },
    ],
    cluesDown: [
      { num: 1, clue: 'Rustic wooden house' },
      { num: 2, clue: 'Very enthusiastic' },
      { num: 3, clue: 'Wager' },
      { num: 4, clue: 'Board or video pastime' },
      { num: 5, clue: 'Deli meat, or an overactor' },
    ],
  },
  {
    grid: ['##SUM', '#ELSE', 'GREEN', 'AGES#', 'LOP##'],
    cluesAcross: [
      { num: 1, clue: 'Total' },
      { num: 4, clue: 'Otherwise' },
      { num: 5, clue: 'Grass\'s color' },
      { num: 6, clue: 'Grows old, or eras' },
      { num: 7, clue: 'Chop off' },
    ],
    cluesDown: [
      { num: 1, clue: 'Nighttime rest' },
      { num: 2, clue: 'Puts to work' },
      { num: 3, clue: 'Adult males' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Girl, informally' },
    ],
  },
  {
    grid: ['##AGE', '#GRAY', 'ALIVE', 'DOSE#', 'OWE##'],
    cluesAcross: [
      { num: 1, clue: 'How old you are' },
      { num: 4, clue: 'Between black and white' },
      { num: 5, clue: 'Not dead' },
      { num: 6, clue: 'Amount of medicine' },
      { num: 7, clue: 'Be in debt for' },
    ],
    cluesDown: [
      { num: 1, clue: 'Come up' },
      { num: 2, clue: 'Handed over, past tense' },
      { num: 3, clue: 'Seeing organ' },
      { num: 4, clue: 'Soft light' },
      { num: 5, clue: 'Fuss' },
    ],
  },
  {
    grid: ['ERR##', 'LOAF#', 'MODEL', '#FILE', '##OLD'],
    cluesAcross: [
      { num: 1, clue: 'Make a mistake' },
      { num: 4, clue: 'Bread shape' },
      { num: 6, clue: 'Small-scale replica' },
      { num: 8, clue: 'Document folder' },
      { num: 9, clue: 'Not young' },
    ],
    cluesDown: [
      { num: 1, clue: 'Shade tree' },
      { num: 2, clue: 'Top of a house' },
      { num: 3, clue: 'Broadcasts music' },
      { num: 5, clue: 'Dropped, past tense' },
      { num: 7, clue: 'Guided' },
    ],
  },
  {
    grid: ['##OFF', '#FREE', 'BIBLE', 'UNIT#', 'YET##'],
    cluesAcross: [
      { num: 1, clue: 'Not on' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Sacred Christian book' },
      { num: 6, clue: 'Single measuring piece' },
      { num: 7, clue: 'Up to now' },
    ],
    cluesDown: [
      { num: 1, clue: 'Path around a planet' },
      { num: 2, clue: 'Sensed, or a soft fabric' },
      { num: 3, clue: 'Charge for a service' },
      { num: 4, clue: 'Okay, or a penalty payment' },
      { num: 5, clue: 'Purchase' },
    ],
  },
  {
    grid: ['OFF##', 'LORD#', 'DRAIN', '#MICE', '##LET'],
    cluesAcross: [
      { num: 1, clue: 'Not on' },
      { num: 4, clue: 'Manor\'s master' },
      { num: 6, clue: 'Sink outlet' },
      { num: 8, clue: 'Plural of mouse' },
      { num: 9, clue: 'Allow' },
    ],
    cluesDown: [
      { num: 1, clue: 'Not young' },
      { num: 2, clue: 'Shape, or a document' },
      { num: 3, clue: 'Physically weak' },
      { num: 5, clue: 'Board-game cubes' },
      { num: 7, clue: 'Basketball hoop\'s mesh' },
    ],
  },
  {
    grid: ['##HAM', '#CARE', 'CABIN', 'AVID#', 'NET##'],
    cluesAcross: [
      { num: 1, clue: 'Deli meat, or an overactor' },
      { num: 4, clue: 'Concern' },
      { num: 5, clue: 'Rustic wooden house' },
      { num: 6, clue: 'Very enthusiastic' },
      { num: 7, clue: 'Basketball hoop\'s mesh' },
    ],
    cluesDown: [
      { num: 1, clue: 'Regular routine' },
      { num: 2, clue: 'Very dry' },
      { num: 3, clue: 'Adult males' },
      { num: 4, clue: 'Underground hollow' },
      { num: 5, clue: 'Soda container' },
    ],
  },
  {
    grid: ['##HAG', '#CAGE', 'LABEL', 'ARID#', 'MET##'],
    cluesAcross: [
      { num: 1, clue: 'Old crone' },
      { num: 4, clue: 'Bird enclosure' },
      { num: 5, clue: 'Sticker with info' },
      { num: 6, clue: 'Very dry' },
      { num: 7, clue: 'Encountered' },
    ],
    cluesDown: [
      { num: 1, clue: 'Regular routine' },
      { num: 2, clue: 'Grown old' },
      { num: 3, clue: 'Hair-styling goop' },
      { num: 4, clue: 'Concern' },
      { num: 5, clue: 'On the run' },
    ],
  },
  {
    grid: ['##FEW', '#FADE', 'ORBIT', 'FELT#', 'FEE##'],
    cluesAcross: [
      { num: 1, clue: 'Not many' },
      { num: 4, clue: 'Gradually disappear' },
      { num: 5, clue: 'Path around a planet' },
      { num: 6, clue: 'Sensed, or a soft fabric' },
      { num: 7, clue: 'Charge for a service' },
    ],
    cluesDown: [
      { num: 1, clue: 'Fictional story with a moral' },
      { num: 2, clue: 'Revise text' },
      { num: 3, clue: 'Not dry' },
      { num: 4, clue: 'No cost' },
      { num: 5, clue: 'Not on' },
    ],
  },
  {
    grid: ['ELF##', 'GOLD#', 'GROUP', '#DONE', '##DEN'],
    cluesAcross: [
      { num: 1, clue: 'Santa’s helper' },
      { num: 4, clue: 'Precious yellow metal' },
      { num: 6, clue: 'Team or cluster' },
      { num: 8, clue: 'Finished' },
      { num: 9, clue: 'Cozy family room' },
    ],
    cluesDown: [
      { num: 1, clue: 'Breakfast oval' },
      { num: 2, clue: 'Manor\'s master' },
      { num: 3, clue: 'Overflowing water' },
      { num: 5, clue: 'Desert sand hill' },
      { num: 7, clue: 'Writing tool' },
    ],
  },
  {
    grid: ['##SUP', '#ELSE', 'GREEN', 'AGES#', 'LOP##'],
    cluesAcross: [
      { num: 1, clue: 'Have supper' },
      { num: 4, clue: 'Otherwise' },
      { num: 5, clue: 'Grass\'s color' },
      { num: 6, clue: 'Grows old, or eras' },
      { num: 7, clue: 'Chop off' },
    ],
    cluesDown: [
      { num: 1, clue: 'Nighttime rest' },
      { num: 2, clue: 'Puts to work' },
      { num: 3, clue: 'Writing tool' },
      { num: 4, clue: 'Therefore, formally' },
      { num: 5, clue: 'Girl, informally' },
    ],
  },
  {
    grid: ['##HUB', '#BONE', 'FRUIT', 'EAST#', 'EYE##'],
    cluesAcross: [
      { num: 1, clue: 'Central point' },
      { num: 4, clue: 'Skeleton piece' },
      { num: 5, clue: 'Apple or banana' },
      { num: 6, clue: 'Sunrise direction' },
      { num: 7, clue: 'Seeing organ' },
    ],
    cluesDown: [
      { num: 1, clue: 'Where you live' },
      { num: 2, clue: 'Single measuring piece' },
      { num: 3, clue: 'Wager' },
      { num: 4, clue: 'Donkey\'s cry' },
      { num: 5, clue: 'Charge for a service' },
    ],
  },
];
